steps:
  # Install dependencies and TypeScript
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install', '-g', 'typescript', 'vite']
    dir: 'frontend'

  # Install project dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'

  # Install platform-specific Rollup
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install', '@rollup/rollup-linux-x64-gnu', '--save-optional']
    dir: 'frontend'

  # Build the frontend
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'social-media-manager', '.']

  # Run the build command in the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--platform', 'linux/amd64', '--rm', 'social-media-manager', 'npm', 'run', 'build']

  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '--platform', 'linux/amd64',
           '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/social-media-manager',
           '-f', 'docker/backend/Dockerfile',
           '.']

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/social-media-manager']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'social-media-manager'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/social-media-manager'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

timeout: '1800s' 